### ISSUE TITLE
cc configurator plugin

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/creativecommons-wordpress-plugin#9]
How is this plugin different or alike? http://www.codetrax.org/projects/wp-cc-configurator/wiki

Do we need to do anything here or should we just congratulate the developer?

**Comment by tarmot** [comment]
CC-configurator is an old acquaintance. We started working on this new official plugin because even CC-configurator did not have a sufficient feature set. It's missing support for multisite, and does not have author-specific license defaults. I'm glad to see they're back in active development, as the plugin was passive two years ago.

**Comment by cogdog** [comment]
It recently went "Deprecated" with lots of all caps warnings. Sad.  https://wordpress.org/plugins/creative-commons-configurator-1/

**Comment by robmyers** [comment]
Oh yes that's sad. It's good they're giving their users a heads up and suggestions for a migration path. We should look at their work again and see if there is any functionality we don't have, or any useful insights into how to handle licensing at the code level.

**Comment by lovethelord** [comment]
What is this!?

**Comment by robmyers** [comment]
It's a WordPress plugin that allows you to apply a Creative Commons license to your blog and/or photos.
